//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CN100.EnterprisePlatform.MQ.Configuration
{


    /// <summary>
    /// The MQClientSection Configuration Section.
    /// </summary>
    public partial class MQClientSection : global::System.Configuration.ConfigurationSection
    {

        #region Singleton Instance
        /// <summary>
        /// The XML name of the MQClientSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string MQClientSectionSectionName = "mQClientSection";

        /// <summary>
        /// Gets the MQClientSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public static global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection Instance
        {
            get
            {
                return ((global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection)(global::System.Configuration.ConfigurationManager.GetSection(global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.MQClientSectionSectionName)));
            }
        }
        #endregion

        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string XmlnsPropertyName = "xmlns";

        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.XmlnsPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.XmlnsPropertyName]));
            }
        }
        #endregion

        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion

        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string NamePropertyName = "name";

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.NamePropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false, DefaultValue = "CN100MQServer")]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.NamePropertyName]));
            }
            set
            {
                base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.NamePropertyName] = value;
            }
        }
        #endregion

        #region Ip Property
        /// <summary>
        /// The XML name of the <see cref="Ip"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string IpPropertyName = "ip";

        /// <summary>
        /// Gets or sets the Ip.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The Ip.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.IpPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false, DefaultValue = "127.0.0.1")]
        public virtual string Ip
        {
            get
            {
                return ((string)(base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.IpPropertyName]));
            }
            set
            {
                base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.IpPropertyName] = value;
            }
        }
        #endregion

        #region Port Property
        /// <summary>
        /// The XML name of the <see cref="Port"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string PortPropertyName = "port";

        /// <summary>
        /// Gets or sets the Port.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The Port.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.PortPropertyName, IsRequired = false, IsKey = false, IsDefaultCollection = false, DefaultValue = 10905)]
        public virtual int Port
        {
            get
            {
                return ((int)(base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.PortPropertyName]));
            }
            set
            {
                base[global::CN100.EnterprisePlatform.MQ.Configuration.MQClientSection.PortPropertyName] = value;
            }
        }
        #endregion
    }
}
