//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CN100.EnterprisePlatform.WebTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://www.baidu.com/");
            request1.ThinkTime = 29;
            ExtractHiddenFields extractionRule1 = new ExtractHiddenFields();
            extractionRule1.Required = true;
            extractionRule1.HtmlDecode = true;
            extractionRule1.ContextParameterName = "1";
            request1.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://suggestion.baidu.com/su");
            request2.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request2.QueryStringParameters.Add("wd", "a", false, false);
            request2.QueryStringParameters.Add("p", "3", false, false);
            request2.QueryStringParameters.Add("cb", "window.bdsug.sug", false, false);
            request2.QueryStringParameters.Add("sid", "1288_1396_1267_1421_1418_1186_1283_1286_1293_1367_1389", false, false);
            request2.QueryStringParameters.Add("t", "1348206722537", false, false);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://suggestion.baidu.com/su");
            request3.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request3.QueryStringParameters.Add("wd", "as", false, false);
            request3.QueryStringParameters.Add("p", "3", false, false);
            request3.QueryStringParameters.Add("cb", "window.bdsug.sug", false, false);
            request3.QueryStringParameters.Add("sid", "1288_1396_1267_1421_1418_1186_1283_1286_1293_1367_1389", false, false);
            request3.QueryStringParameters.Add("t", "1348206722758", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://suggestion.baidu.com/su");
            request4.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request4.QueryStringParameters.Add("wd", "asp", false, false);
            request4.QueryStringParameters.Add("p", "3", false, false);
            request4.QueryStringParameters.Add("cb", "window.bdsug.sug", false, false);
            request4.QueryStringParameters.Add("sid", "1288_1396_1267_1421_1418_1186_1283_1286_1293_1367_1389", false, false);
            request4.QueryStringParameters.Add("t", "1348206722899", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://suggestion.baidu.com/su");
            request5.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request5.QueryStringParameters.Add("wd", "asp.", false, false);
            request5.QueryStringParameters.Add("p", "3", false, false);
            request5.QueryStringParameters.Add("cb", "window.bdsug.sug", false, false);
            request5.QueryStringParameters.Add("sid", "1288_1396_1267_1421_1418_1186_1283_1286_1293_1367_1389", false, false);
            request5.QueryStringParameters.Add("t", "1348206723106", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://suggestion.baidu.com/su");
            request6.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request6.QueryStringParameters.Add("wd", "asp.ne", false, false);
            request6.QueryStringParameters.Add("p", "3", false, false);
            request6.QueryStringParameters.Add("cb", "window.bdsug.sug", false, false);
            request6.QueryStringParameters.Add("sid", "1288_1396_1267_1421_1418_1186_1283_1286_1293_1367_1389", false, false);
            request6.QueryStringParameters.Add("t", "1348206723418", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://suggestion.baidu.com/su");
            request7.ThinkTime = 2;
            request7.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request7.QueryStringParameters.Add("wd", "asp.net", false, false);
            request7.QueryStringParameters.Add("p", "3", false, false);
            request7.QueryStringParameters.Add("cb", "window.bdsug.sug", false, false);
            request7.QueryStringParameters.Add("sid", "1288_1396_1267_1421_1418_1186_1283_1286_1293_1367_1389", false, false);
            request7.QueryStringParameters.Add("t", "1348206723540", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://www.baidu.com/s");
            request8.Encoding = System.Text.Encoding.GetEncoding("gb2312");
            request8.QueryStringParameters.Add("wd", "asp.net", false, false);
            request8.QueryStringParameters.Add("rsv_bp", this.Context["$HIDDEN1.rsv_bp"].ToString(), false, false);
            request8.QueryStringParameters.Add("rsv_spt", this.Context["$HIDDEN1.rsv_spt"].ToString(), false, false);
            request8.QueryStringParameters.Add("rsv_sug3", "6", false, false);
            request8.QueryStringParameters.Add("rsv_sug4", "553", false, false);
            request8.QueryStringParameters.Add("rsv_sug1", "2", false, false);
            request8.QueryStringParameters.Add("inputT", "4394", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://share.baidu.com/getsharenum");
            request9.QueryStringParameters.Add("urls", "7127156363585374272,16865185710338639105,10565884470600169400,1165714917451780884" +
                    "9,17536678826032455059,12729630378874839467,12639570885692887916,182535218374730" +
                    "10988,5592967693026493460", false, false);
            request9.QueryStringParameters.Add("callback", "bds.se.like.giveData", false, false);
            yield return request9;
            request9 = null;
        }
    }
}
